[project]
name = "mydbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">3.12,<3.13"
dependencies = [
    "dbt>=1.0.0.38.36",
    "dbt-duckdb>=1.9.2",
    "sqlfluff>=3.3.1",
]
