version: 2

seeds:
  - name: rvsoft_cv_groups
    description: "BAO product groups ids mapping to descriptions"
    columns:
      - name: grupp
        tests:
          - unique
          - not_null
      - name: grupinimi
        tests:
          - unique
          - not_null
