version: 2

models:
  - name: stg_bao__sales_and_purchases
    description: "Sold items 2022-01-01..."
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - firma_id
            - jrk
            - siffer
            - vkogus
            - skogus
            - liik
    columns:
      - name: siffer
        description: "sku of the product"
        data_tests:
          - not_null

      - name: firma_id
        description: "Customer's code in BAO's system"
        data_tests:
          - not_null

  - name: stg_fi__stocks
    description: "Finland - stocks and prices"
    columns:
      - name: mekofi_code
        description: "sku of the product"
        data_tests:
          - unique
          - not_null

  - name: stg_cei__prices
    description: "CEI - stocks and prices"
    columns:
      - name: code
        description: "sku of the product"
        data_tests:
          - unique
          - not_null

  - name: stg_cei__db_factoryitems
    description: "existing CEI items in 'items' table in production db"
    columns:
      - name: item_id
        description: "id in table 'item'"
        data_tests:
          - unique
          - not_null

      - name: code
        description: "sku of the product"
        data_tests:
          - unique
          - not_null

      - name: manufacturer_id
        description: "foreign key to 'manufacturer' table in the production db"

  - name: int_cei_items_filtered_for_insert.sql
    description: "pricelist products that do not exist in database 'items' table"
    columns:
      - name: code
        description: "sku of the product"
        data_tests:
          - unique
          - not_null

      - name: manufacturer_id
        description: "foreign key for manufacturer's id"

  - name: stg_fm__prices
    description: "fm pricelist"
    columns:
      - name: brand
      - name: product_category
      - name: code
        description: "sku of the product"
        data_tests:
          - unique
          - not_null
      - name: sub_segment
      - name: lvcv
        description: "commercial or light vehicle"
      - name: cluster_rebates
      - name: invoice
        description: "price in Euros for us"
      - name: invoice_1
      - name: increase_pep
      - name: remarks
      - name: stg_cei__prices
      - name: status
      - name: invoice_2
      - name: invoice_3
      - name: ds_range

  - name: int_fm_items_filtered_for_update
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - item_id
            - min_order
