version: 2

sources:
  - name: downloads
    meta:
      external_location: "/home/tarmo/bao_tooted/data/processed/balanss_ajalugu.parquet"
    tables:
      - name: sales_history

  - name: bao_products
    meta:
      external_location: "/home/tarmo/bao_tooted/data/raw/LM_MAT.DBF"
    tables:
      - name: stg_bao__products

  - name: bao_stocks
    meta:
      external_location: "/home/tarmo/bao_tooted/data/raw/LL020000.DBF"
    tables:
      - name: stg_bao__stocks

  - name: bao_firma
    meta:
      external_location: "/home/tarmo/bao_tooted/data/raw/FIRMA.DBF"
    tables:
      - name: stg_bao__firma

  - name: bao_replacements
    meta:
      external_location: "/home/tarmo/bao_tooted/data/raw/ASENDUS.DBF"
    tables:
      - name: stg_bao__replacements

  - name: fi_stocks
    meta:
      external_location: "/mnt/c/Users/tarmos/OneDrive - BALTI AUTOOSAD AS/koivunen/basic_info.csv"
    tables:
      - name: stg_fi__stocks
  - name: zf_pricelist
    meta:
      external_location: "/mnt/c/Users/tarmos/OneDrive - BALTI AUTOOSAD AS/zf/B2 09052025.xlsx"
    tables:
      - name: stg_zf__prices

  - name: postgres_db
