version: 2

sources:
  - name: downloads
    meta:
      external_location: "/home/tarmo/bao_tooted/data/processed/balanss_ajalugu.parquet"
    tables:
      - name: sales_history

  - name: autos_offer
    meta:
      external_location: "/home/tarmo/bao_tooted/data/raw/2025_04_23_autos.csv"
    tables:
      - name: autos
