version: 2

sources:
  - name: downloads
    meta:
      external_location: "/home/tarmo/bao_tooted/data/processed/balanss_ajalugu.parquet"
    tables:
      - name: sales_history

  - name: bao_lmmat
    meta:
      external_location: "/home/tarmo/bao_tooted/data/raw/LM_MAT.DBF"
    tables:
      - name: stg_bao_lmmat

  - name: bao_stock
    meta:
      external_location: "/home/tarmo/bao_tooted/data/raw/LL020000.DBF"
    tables:
      - name: stg_bao_stock

  - name: bao_firma
    meta:
      external_location: "/home/tarmo/bao_tooted/data/raw/FIRMA.DBF"
    tables:
      - name: stg_bao_firma
