version: 2

sources:
  - name: fi_stocks
    meta:
      external_location: "{{ env_var('DBT_EXTERNAL') }}/koivunen/basic_info.csv"
    tables:
      - name: stg_fi__stocks

  - name: zf_pricelist
    meta:
      external_location: "{{ env_var('DBT_EXTERNAL') }}/zf/B2 09052025.xlsx"
    tables:
      - name: stg_zf__prices

  - name: hengst_products
    meta:
      external_location: "{{ env_var('DBT_EXTERNAL') }}/hengst/2024_01_hengst_pricelist.xlsx"
    tables:
      - name: stg_hengst__products

  - name: mann_products
    meta:
      external_location: "{{ env_var('DBT_EXTERNAL') }}/mann_hummel/2025_07_mann_hummel_pricelist.xlsx"
    tables:
      - name: stg_mann__products

  - name: auger_pricelist
    meta:
      external_location: "{{ env_var('DBT_EXTERNAL') }}/auger/2025_04_auger_pricelist.xlsx"
    tables:
      - name: stg_auger__prices

  - name: cei_pricelist
    meta:
      external_location: "{{ env_var('DBT_EXTERNAL') }}/cei/2024_01_cei_pricelist.parquet"
    tables:
      - name: stg_cei__prices

  - name: fm_pricelist
    meta:
      external_location: "{{ env_var('DBT_EXTERNAL') }}/federal_mogul/pep_price_list_2025.xlsx"
    tables:
      - name: stg_fm__prices

  - name: bosch_cv_products
    meta:
      external_location: "{{ env_var('DBT_EXTERNAL') }}/bosch/bosch_cv_2024.xlsx"
    tables:
      - name: stg_bosch__cv_products
